Feature/typescript integration
fairmartsg/eslintconfig pull request #3
Opened 2023-03-03 10:56 UTC by aungkhantkyaw9

## Description

Add typescript eslint to eslint config rules

2023-03-03 12:35 UTC, dmoskovtsov requested changes
- note, you might have to put new dependencies to peer dependencies.

2023-03-03 12:35 UTC, dmoskovtsov commented on index.js
> +        // for files matching this pattern
- Please remove the comment. 
- Please setup a webstorm to use single quotes & reformat this file.

2023-03-03 12:35 UTC, dmoskovtsov commented on package.json
> +    "@typescript-eslint/parser": "^5.54.0",
Use exact versions (unless you build a library). 

   "@typescript-eslint/eslint-plugin": "5.54.0",

2023-03-03 12:35 UTC, dmoskovtsov commented on package.json
> +    "typescript": "^4.9.5"
Same here

2023-03-03 20:48 UTC, aungkhantkyaw9 commented
@dmoskovtsov after testing clean install of yarn in `store` we don't need to move `dependencies` inside `peer-dependencies`. All necessary packages are automatically installed in `store`

2023-03-06 02:41 UTC, dmoskovtsov approved these changes

2023-03-06 02:41 UTC, merged